ALTER TABLE "ShopSettings" DROP COLUMN IF EXISTS "defaultDurationMin";
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "defaultStartTime" TEXT NOT NULL DEFAULT '09:00';
ALTER TABLE "ClassProduct" DROP COLUMN IF EXISTS "durationMin";
ALTER TABLE "ClassProduct" ADD COLUMN IF NOT EXISTS "defaultStartTime" TEXT NOT NULL DEFAULT '09:00';
ALTER TABLE "ClassSession" DROP COLUMN IF EXISTS "endsAt";
