# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "603c34e9ca36ff2b105fecf9383ee475"
name = "Classes (dev)"
application_url = "https://shopify-classes.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_inventory,write_products"

[auth]
redirect_urls = [ "https://shopify-classes.vercel.app/auth/callback" ]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/updated"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
